### ISSUE TITLE
Consider applying `img { image-rendering: pixelated; }` to pixel art images

### ISSUE THREAD

**Issue by mathiasbynens** [rauchg/how-is-this-not-illegal#13]
The Pokémon images are pixel art, and could benefit from 

```css
img {
  image-rendering: pixelated;
}
```

for crisp, authentic rendering (including on high-res displays or when zooming in).
